version: '3.1'
services:
  db:
    image: mysql:5.7
    #conainer_name: db
    restart: always
    env_file:
      - ./.env
    ports:
      - 3306:3306
    volumes:
      - ./database/data:/var/lib/mysql